[package]
name = "kiddo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.40"
unicode-width = "0.1.10"
unicode-xid = "0.2.4"
