import std::nested;

export struct U32 { }

struct String { }

let global: U32 = 42;

function main(mutable argc: U32, argv: [String; 4]) {
    let number: U32 = global;
    let number: U32 = global + number;
    let a = number;
    let b = a;
    let s: std::nested::S = 42;
    let number_of_args: U32 = argc + global + (argv + argc * (4 + std::nested::nested_global));

    let x = 0;
    let x = x + x + x + x + x + x;
}
